/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    dolce_001: THREE.Mesh;
    dolce_002: THREE.Mesh;
    dolce_003: THREE.Mesh;
    dolce_004: THREE.Mesh;
    dolce_005: THREE.Mesh;
    dolce_006: THREE.Mesh;
    dolce_007: THREE.Mesh;
    dolce_008: THREE.Mesh;
    dolce_009: THREE.Mesh;
    dolce_010: THREE.Mesh;
    dolce_011: THREE.Mesh;
    dolce_012: THREE.Mesh;
    dolce_013: THREE.Mesh;
    dolce_014: THREE.Mesh;
  };
  materials: {
    ["dolce_Leather Uph1 Black"]: THREE.MeshStandardMaterial;
    ["dolce_guylian_Oak Matt Natural 2"]: THREE.MeshStandardMaterial;
    ["dolce_Oak Matt Natural 2"]: THREE.MeshStandardMaterial;
    ["dolce_12 - Default"]: THREE.MeshStandardMaterial;
  };
};

export default function Model({ ...props }: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials } = useGLTF("/chair.glb") as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={0.001}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dolce_001.geometry}
          material={materials["dolce_Leather Uph1 Black"]}
          // material-color={"red"}
          position={[-3.9613, 433.6267, -55.777]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dolce_002.geometry}
          material={materials["dolce_guylian_Oak Matt Natural 2"]}
          position={[196.4443, 8, -282.5835]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dolce_003.geometry}
          material={materials["dolce_Oak Matt Natural 2"]}
          position={[-2.3145, 410.5144, -300.0886]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dolce_004.geometry}
          material={materials["dolce_Oak Matt Natural 2"]}
          position={[0, 716.1602, 178.693]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dolce_005.geometry}
          material={materials["dolce_Oak Matt Natural 2"]}
          position={[177.6366, 413, -46.9268]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dolce_006.geometry}
          material={materials["dolce_Oak Matt Natural 2"]}
          position={[-180.1204, 413, -46.9268]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dolce_007.geometry}
          material={materials["dolce_guylian_Oak Matt Natural 2"]}
          position={[178.9854, 378.4128, 226.6725]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dolce_008.geometry}
          material={materials["dolce_guylian_Oak Matt Natural 2"]}
          position={[-3.9613, 443.9236, -55.506]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dolce_009.geometry}
          material={materials["dolce_Oak Matt Natural 2"]}
          position={[-2.3145, 404.3013, 200.7177]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dolce_010.geometry}
          material={materials["dolce_12 - Default"]}
          position={[203.8684, 0, -283.6757]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dolce_011.geometry}
          material={materials["dolce_12 - Default"]}
          position={[-209.4851, 0, -283.6757]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dolce_012.geometry}
          material={materials["dolce_12 - Default"]}
          position={[179.2873, 0, 290.1181]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dolce_013.geometry}
          material={materials["dolce_12 - Default"]}
          position={[-177.6665, 0, 290.1181]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dolce_014.geometry}
          material={materials["dolce_Leather Uph1 Black"]}
          position={[0, 716.1202, 178.8295]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/chair.glb");
